city = ["México", 
        "Estados Unidos",
        "Canadá",
        "Brasil",
        "Argentina",
        "Colombia",
        "Perú",
        "Chile",
        "Reino Unido",
        "Francia",
        "Alemania",
        "Italia",
        "España",
        "Portugal",
        "Paises Bajos(Holanda)",
        "Bélgica",
        "Suiza",
        "Australia",
        "Nueva Zelanda",
        "Japón",
        "China",
        "Corea del Sur",
        "India",
        "Rusia",
        "Sudáfrica",
        "Egipto",
        "Nigeria",
        "Kenia",
        "Emiratos Árabes Unidos(EAU)",
        "Arabia Saudita"
    ]
gender = ["Masculine", "Female", "Other"]
